"use client";

import { useEffect, useState } from "react";

const DISCLAIMER_KEY = "prelegal_disclaimer_shown";

export default function DisclaimerModal() {
  const [visible, setVisible] = useState(false);

  useEffect(() => {
    if (!sessionStorage.getItem(DISCLAIMER_KEY)) {
      setVisible(true);
    }
  }, []);

  function handleDismiss() {
    sessionStorage.setItem(DISCLAIMER_KEY, "1");
    setVisible(false);
  }

  if (!visible) return null;

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 px-4">
      <div className="bg-white rounded-2xl shadow-xl max-w-md w-full p-8">
        <div className="flex items-start gap-3 mb-4">
          <div
            className="flex-shrink-0 w-8 h-8 rounded-full flex items-center justify-center text-white text-sm font-bold"
            style={{ backgroundColor: "#ecad0a" }}
          >
            !
          </div>
          <h2 className="text-lg font-bold pt-0.5" style={{ color: "#032147" }}>
            Important Notice
          </h2>
        </div>

        <p className="text-sm leading-relaxed mb-4" style={{ color: "#032147" }}>
          Documents generated by <strong>Prelegal</strong> are AI-assisted drafts
          for informational purposes only.
        </p>
        <p className="text-sm leading-relaxed mb-6" style={{ color: "#888888" }}>
          They do not constitute legal advice and should not be relied upon
          without review by a qualified attorney. Always consult a legal
          professional before executing any agreement.
        </p>

        <button
          type="button"
          onClick={handleDismiss}
          className="w-full py-2.5 px-4 rounded-lg text-white text-sm font-semibold transition-opacity hover:opacity-90"
          style={{ backgroundColor: "#753991" }}
        >
          I understand — Continue
        </button>
      </div>
    </div>
  );
}
